#!/bin/bash

# Import the workspace into JupyterLab
jupyter lab workspaces import workspace.json

# Download CSV file
# wget -q -O ActinometricData.csv "https://meteolab.ru/downloads/ActinometricData.csv"
